# INTERPRETĂRI PENTRU SEXUAL (EXTINSE ȘI DETALIATE)
sexual_interpretations = {
    "Sun": {
        "ARI": "**Energie sexuală directă și pasională.** Nevoie puternică de inițiativă și aventură în viața intimă. Atracție față de partenerii energici și independenți. Stil sexual competitiv și entuziast, cu preferință pentru rapiditate și spontaneitate. Se simte revitalizat prin activitatea sexuală energică.",
        "TAU": "**Sensualitate profundă și persistentă.** Valorează plăcerea fizică și comoditatea în intimitate. Ritm sexual lent dar intens, cu accent pe contactul fizic prolongat. Atracție pentru parteneri stabili și fiabili. Conexiune puternică între sexualitate și securitate emoțională.",
        "GEM": "**Curiozitate sexuală și versatilitate.** Nevoie de varietate și stimulare mentală în viața intimă. Comunicare verbală importantă în pat. Atracție pentru parteneri inteligenți și vorbăreți. Stil sexual jucăuș și experimental, cu interes pentru noi tehnici.",
        "CAN": "**Intimitate emoțională profundă.** Conexiune puternică între sexualitate și sentimente. Nevoie de securitate și încredere pentru a se deschide complet. Stil sexual nurturing și protector. Atracție pentru parteneri care oferă stabilitate emoțională.",
        "LEO": "**Dramatism și generozitate sexuală.** Nevoie de admirație și recunoaștere în pat. Stil sexual creativ și expresiv, cu accent pe performanță. Atracție pentru parteneri care îi tratează ca regii/reginele dormitorului. Sexualitatea este o formă de autoexprimare.",
        "VIR": "**Precizie și atenție la detalii.** Nevoie de perfecțiune și serviciu în viața intimă. Stil sexual meticulos și atent la nevoile partenerului. Atracție pentru parteneri sănătoși și ordonați. Importanța igienei și a preparării în ritualul sexual.",
        "LIB": "**Armonie și estetică sexuală.** Nevoie de echilibru și frumusețe în experiențele intime. Stil sexual diplomatic și concentrat pe plăcerea reciprocă. Atracție pentru parteneri armonioși și cu simț estetic. Mediuul romantic este crucial.",
        "SCO": "**Intensitate și transformare sexuală.** Nevoie de conexiuni profonde și transformatoare. Stil sexual pasional și investigativ, cu interes pentru tabuurile sexuale. Atracție pentru parteneri misterioși și intensi. Sexualitatea ca formă de eliberare emoțională.",
        "SAG": "**Aventură și expansiune sexuală.** Nevoie de libertate și explorare în viața intimă. Stil sexual optimist și filosofic, cu interes pentru practici exotice. Atracție pentru parteneri aventuroși și deschiși mental. Sexualitatea ca călătorie de descoperire.",
        "CAP": "**Disciplină și ambiție sexuală.** Nevoie de structură și realizare în viața intimă. Stil sexual responsabil și concentrat pe obiective pe termen lung. Atracție pentru parteneri ambițioși și maturi. Sexualitatea ca formă de realizare personală.",
        "AQU": "**Inovație și nonconformism sexual.** Nevoie de libertate și originalitate în practicile intime. Stil sexual experimental și detașat emoțional, cu interes pentru tehnologie și inovație. Atracție pentru parteneri unici și independenți.",
        "PIS": "**Compașiune și spiritualitate sexuală.** Nevoie de conexiune spirituală și fuziune emoțională. Stil sexual romantic și intuitiv, cu sensibilitate crescută la energiile partenerului. Atracție pentru parteneri sensibili și artistici. Sexualitatea ca experiență transcendentă."
    },
    "Moon": {
        "ARI": "**Nevoi emoționale directe și impulsive.** Reacționează rapid și pasional în situații intime. Nevoie de independență și entuziasm emoțional. Ritm sexual dictat de stările emoționale momentane. Conexiune puternică între dispoziție și dorință sexuală.",
        "TAU": "**Stabilitate emoțională și senzualitate.** Nevoie de comfort și securitate emoțională pentru a se simți conectat sexual. Ritm sexual constant și previzibil. Atracție pentru parteneri care oferă stabilitate. Plăcerea fizică este profund legată de bunăstarea emoțională.",
        "GEM": "**Curiozitate emoțională și versatilitate.** Nevoie de comunicare și schimb emoțional în intimitate. Stil sexual adaptabil la stările de spirit ale partenerului. Atracție pentru parteneri care stimulează mental. Dorința sexuală influențată de conexiunea intelectuală.",
        "CAN": "**Sensibilitate emoțională profundă.** Nevoie de conexiune emoțională și siguranță pentru intimitate. Stil sexual protective și nurturing. Atracție pentru parteneri care oferă confort emoțional. Sexualitatea strâns legată de sentimentul de apartenență.",
        "LEO": "**Dramatism emoțional și mândrie.** Nevoie de admirație și recunoaștere emoțională. Stil sexual generos și expresiv emoțional. Atracție pentru parteneri care îi fac să se simtă speciali. Dorința sexuală amplificată de încrederea în sine.",
        "VIR": "**Analitică emoțională și serviciu.** Nevoie de ordine și utilitate în expresia emoțională. Stil sexual atent la detalii emoționale. Atracție pentru parteneri care apreciază atenția la detalii. Curățenia emoțională este importantă pentru intimitate.",
        "LIB": "**Armonie emoțională și parteneriat.** Nevoie de echilibru și frumusețe în relațiile emoționale. Stil sexual diplomatic și concentrat pe armonie. Atracție pentru parteneri grațioși și echilibrați. Starea emoțională influențează direct dorința sexuală.",
        "SCO": "**Intensitate emoțională și transformare.** Nevoie de profunzime și autenticitate emoțională. Stil sexual pasional și investigativ emoțional. Atracție pentru parteneri intensi și misterioși. Ciclurile emoționale profunde influențează sexualitatea.",
        "SAG": "**Optimism emoțional și aventură.** Nevoie de libertate și expansiune emoțională. Stil sexual entuziast și filosofic. Atracție pentru parteneri care îi inspiră și îi fac să crească. Stările emoționale pozitive amplifică dorința sexuală.",
        "CAP": "**Responsabilitate emoțională și control.** Nevoie de structură și realizare emoțională. Stil sexual disciplinat și concentrat pe obiective. Atracție pentru parteneri maturi și responsabili. Stabilitatea emoțională este esențială pentru intimitate.",
        "AQU": "**Independență emoțională și inovație.** Nevoie de libertate și originalitate emoțională. Stil sexual detașat dar progresist. Atracție pentru parteneri unici și independenți. Conexiunea emoțională bazată pe interese intelectuale comune.",
        "PIS": "**Empatie emoțională și spiritualitate.** Nevoie de conexiune spirituală și compasiune. Stil sexual intuitiv și sensibil la energiile partenerului. Atracție pentru parteneri sensibili și creativi. Stările emoționale sunt profund conectate cu experiența sexuală."
    },
    "Venus": {
        "ARI": "**Atracție pasională și directă.** Se îndrăgostește rapid și cu intensitate. Preferă parteneri energici și provocatori. Expresia romantică directă și spontană. Valorează entuziasmul și aventura în relații.",
        "TAU": "**Sensualitate și devotament.** Atracție pentru parteneri stabili și senzuali. Expresia romantică prin contact fizic și gesturi concrete. Valorează comoditatea și securitatea în relații. Ritm romantic lent dar profund.",
        "GEM": "**Curiozitate romantică și comunicare.** Atracție pentru parteneri inteligenți și vorbăreți. Expresia romantică prin conversație și schimb intelectual. Valorează varietatea și distractia în relații.",
        "CAN": "**Protecție și nurturing romantic.** Atracție pentru parteneri care oferă securitate emoțională. Expresia romantică prin grijă și protecție. Valorează conexiunea emoțională profundă și familia.",
        "LEO": "**Dramatism și generozitate romantică.** Atracție pentru parteneri care îi admiră și îi tratează special. Expresia romantică extravagantă și creativă. Valorează recunoașterea și aprecierea în relații.",
        "VIR": "**Devotament și serviciu romantic.** Atracție pentru parteneri sănătoși și organizați. Expresia romantică prin atenție la detalii și acte de serviciu. Valorează utilitatea și perfecțiunea în relații.",
        "LIB": "**Armonie și parteneriat romantic.** Atracție pentru parteneri grațioși și echilibrați. Expresia romantică prin gesturi estetice și diplomatice. Valorează echilibrul și frumusețea în relații.",
        "SCO": "**Pasiune și intensitate romantică.** Atracție pentru parteneri misterioși și intensi. Expresia romantică profundă și transformatoare. Valorează autenticitatea și profunzimea în relații.",
        "SAG": "**Aventură și expansiune romantică.** Atracție pentru parteneri aventuroși și deschiși mental. Expresia romantică prin explorare și învățare comună. Valorează libertatea și creșterea în relații.",
        "CAP": "**Stabilitate și ambiție romantică.** Atracție pentru parteneri maturi și ambițioși. Expresia romantică prin angajament și realizări comune. Valorează responsabilitatea și succesul în relații.",
        "AQU": "**Prietenie și originalitate romantică.** Atracție pentru parteneri unici și independenți. Expresia romantică neconvențională și intelectuală. Valorează libertatea și inovația în relații.",
        "PIS": "**Compașiune și romanticism spiritual.** Atracție pentru parteneri sensibili și creativi. Expresia romantică prin compasiune și conexiune spirituală. Valorează visul și fuziunea emoțională în relații."
    },
    "Mars": {
        "ARI": "**Energie sexuală directă și competitivă.** Stil sexual entuziast și impulsiv. Nevoie de provocare și aventură în pat. Atracție pentru parteneri energici care pot ține pasul. Dorința sexuală puternică și frecventă.",
        "TAU": "**Persistență sexuală și senzualitate.** Stil sexual lent dar intens și persistent. Nevoie de comfort și plăcere fizică prolongată. Atracție pentru parteneri stabili și senzuali. Ritm sexual constant și fiabil.",
        "GEM": "**Versatilitate sexuală și comunicare.** Stil sexual jucăuș și experimental. Nevoie de varietate și stimulare mentală. Atracție pentru parteneri vorbăreți și creativi. Dorința sexuală influențată de curiozitate.",
        "CAN": "**Protecție sexuală și sensibilitate.** Stil sexual emotional și protective. Nevoie de securitate și conexiune emoțională. Atracție pentru parteneri nurturing și sensibili. Sexualitatea strâns legată de sentimente.",
        "LEO": "**Dramatism sexual și încredere.** Stil sexual generos și performativ. Nevoie de admirație și recunoaștere. Atracție pentru parteneri care îi tratează ca staruri. Dorința sexuală amplificată de mândrie.",
        "VIR": "**Precizie sexuală și serviciu.** Stil sexual meticulos și atent la detalii. Nevoie de ordine și perfecțiune. Atracție pentru parteneri sănătoși și organizați. Ritualul și prepararea importante în sexualitate.",
        "LIB": "**Armonie sexuală și parteneriat.** Stil sexual diplomatic și concentrat pe plăcerea reciprocă. Nevoie de echilibru și frumusețe. Atracție pentru parteneri grațioși și armonioși. Mediuul romantic crucial pentru dorință.",
        "SCO": "**Intensitate sexuală și transformare.** Stil sexual pasional și investigativ. Nevoie de profunzime și autenticitate. Atracție pentru parteneri intensi și misterioși. Dorința sexuală puternică și transformatoare.",
        "SAG": "**Aventură sexuală și expansiune.** Stil sexual optimist și explorator. Nevoie de libertate și varietate. Atracție pentru parteneri aventuroși și deschiși mental. Sexualitatea ca formă de descoperire.",
        "CAP": "**Ambiție sexuală și disciplină.** Stil sexual responsabil și concentrat pe obiective. Nevoie de structură și realizare. Atracție pentru parteneri maturi și ambițioși. Dorința sexuală controlată și direcționată.",
        "AQU": "**Inovație sexuală și independență.** Stil sexual experimental și nonconformist. Nevoie de libertate și originalitate. Atracție pentru parteneri unici și independenți. Sexualitatea ca formă de expresie personală.",
        "PIS": "**Intuiție sexuală și compasiune.** Stil sexual romantic și sensibil. Nevoie de conexiune spirituală și fuziune. Atracție pentru parteneri sensibili și creativi. Dorința sexuală influențată de imaginație."
    },
    "Pluto": {
        "ARI": "**Transformare sexuală prin acțiune.** Nevoie de putere și control în viața intimă. Atracție pentru parteneri puternici și independenți. Stil sexual intens și transformator. Sexualitatea ca formă de eliberare personală.",
        "TAU": "**Transformare a valorilor sexuale.** Nevoie de securitate și posesie în intimitate. Atracție pentru parteneri stabili dar transformatori. Stil sexual profund și regenerator. Sexualitatea conectată cu supraviețuirea.",
        "GEM": "**Transformare mentală sexuală.** Nevoie de comunicare profundă și schimb intelectual. Atracție pentru parteneri care provoacă gândirea. Stil sexual investigativ și transformator. Sexualitatea ca formă de descoperire mentală.",
        "CAN": "**Transformare emoțională sexuală.** Nevoie de conexiune emoțională profundă și siguranță. Atracție pentru parteneri care transformă viața emoțională. Stil sexual protective și regenerator. Sexualitatea conectată cu ciclurile emoționale.",
        "LEO": "**Transformare creativă sexuală.** Nevoie de expresie personală și recunoaștere. Atracție pentru parteneri care îi transformă imaginea de sine. Stil sexual dramatic și regenerator. Sexualitatea ca formă de renaștere personală.",
        "VIR": "**Transformare prin serviciu sexual.** Nevoie de perfecțiune și regenerare prin serviciu. Atracție pentru parteneri care îi transformă viața practică. Stil sexual meticulos și purificator. Sexualitatea ca formă de vindecare.",
        "LIB": "**Transformare a parteneriatului sexual.** Nevoie de echilibru și regenerare în relații. Atracție pentru parteneri care transformă dinamica relației. Stil sexual armonios și transformator. Sexualitatea ca formă de reechilibrare.",
        "SCO": "**Transformare sexuală profundă.** Nevoie de profunzime și regenerare totală. Atracție pentru parteneri intensi și transformatori. Stil sexual pasional și regenerator. Sexualitatea ca experiență de renaștere.",
        "SAG": "**Transformare filosofică sexuală.** Nevoie de expansiune și regenerare prin învățare. Atracție pentru parteneri care îi transformă viziunea asupra vieții. Stil sexual explorator și transformator. Sexualitatea ca călătorie spirituală.",
        "CAP": "**Transformare structurală sexuală.** Nevoie de putere și regenerare prin realizare. Atracție pentru parteneri ambițioși și transformatori. Stil sexual disciplinat și regenerator. Sexualitatea ca formă de construcție personală.",
        "AQU": "**Transformare colectivă sexuală.** Nevoie de libertate și regenerare prin inovație. Atracție pentru parteneri unici care transformă perspectiva asupra societății. Stil sexual experimental și transformator. Sexualitatea ca formă de revoluție personală.",
        "PIS": "**Transformare spirituală sexuală.** Nevoie de fuziune și regenerare spirituală. Atracție pentru parteneri sensibili care transformă conexiunea cu divinul. Stil sexual transcendent și regenerator. Sexualitatea ca experiență mistică."
    }
}
