import pandas as pd
import base64
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
import io

class ExportManager:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        
    def generate_pdf(self, planetary_data, houses_data, birth_info):
        """Generate PDF report of the horoscope"""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        story = []
        
        # Title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Heading1'],
            textColor=colors.HexColor('#f1c40f'),
            spaceAfter=30,
            alignment=1
        )
        story.append(Paragraph("1.Chart Horoscope - Cosmic Vintage Report", title_style))
        
        # Birth information
        story.append(Paragraph("Birth Information", self.styles['Heading2']))
        birth_text = f"""
        Date: {birth_info['date']}<br/>
        Time: {birth_info['time']}<br/>
        Place: {birth_info['place']}<br/>
        Coordinates: {birth_info['latitude']}°N, {birth_info['longitude']}°E
        """
        story.append(Paragraph(birth_text, self.styles['Normal']))
        story.append(Spacer(1, 20))
        
        # Planetary positions table
        story.append(Paragraph("Planetary Positions", self.styles['Heading2']))
        table_data = [['Planet', 'Position', 'Sign', 'House', 'Retrograde']]
        
        for planet, data in planetary_data.items():
            table_data.append([
                planet,
                f"{data['position']:.2f}°",
                data['sign'],
                str(data['house']),
                'Yes' if data.get('retrograde', False) else 'No'
            ])
        
        table = Table(table_data)
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#302b63')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8f9fa')),
            ('TEXTCOLOR', (0, 1), (-1, -1), colors.black),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey)
        ]))
        story.append(table)
        story.append(Spacer(1, 30))
        
        # Footer
        footer_text = f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M')} | 1.Chart Horoscope v2.42"
        story.append(Paragraph(footer_text, self.styles['Italic']))
        
        doc.build(story)
        buffer.seek(0)
        return buffer
    
    def generate_text_report(self, planetary_data, houses_data, birth_info):
        """Generate plain text report"""
        report = []
        report.append("=" * 50)
        report.append("1.CHART HOROSCOPE - COSMIC VINTAGE")
        report.append("=" * 50)
        report.append("")
        report.append("BIRTH INFORMATION:")
        report.append(f"Date: {birth_info['date']}")
        report.append(f"Time: {birth_info['time']}")
        report.append(f"Place: {birth_info['place']}")
        report.append(f"Coordinates: {birth_info['latitude']}°N, {birth_info['longitude']}°E")
        report.append("")
        report.append("PLANETARY POSITIONS:")
        report.append("-" * 30)
        
        for planet, data in planetary_data.items():
            retrograde = " (R)" if data.get('retrograde', False) else ""
            report.append(f"{planet:12} {data['position']:5.2f}° {data['sign']:12} House {data['house']}{retrograde}")
        
        report.append("")
        report.append("Generated by 1.Chart Horoscope v2.42")
        report.append(f"Report date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        
        return "\n".join(report)
    
    def generate_csv_data(self, planetary_data, houses_data, birth_info):
        """Generate CSV data export"""
        # Planetary data
        planets_df = pd.DataFrame([
            {
                'planet': planet,
                'position': data['position'],
                'sign': data['sign'],
                'house': data['house'],
                'retrograde': data.get('retrograde', False),
                'longitude': data.get('longitude', 0)
            }
            for planet, data in planetary_data.items()
        ])
        
        # Houses data
        houses_df = pd.DataFrame([
            {
                'house': house,
                'sign': data['sign'],
                'angle': data['angle'],
                'degrees': data['degrees']
            }
            for house, data in houses_data.items()
        ])
        
        return planets_df.to_csv(index=False), houses_df.to_csv(index=False)
